'use strict';

// ── Constants ──────────────────────────────────────────────────
const DATA_URL    = 'data/flashcards.csv';
const VC_KEY      = 'vocab_v1';
const SESSION_SIZE = 5;
const MAX_RETRIES  = 2;
const API_URL      = '/.netlify/functions/vocabulary';

// ── DOM helpers ────────────────────────────────────────────────
const $ = id => document.getElementById(id);

// ── State ──────────────────────────────────────────────────────
let allCards      = [];    // [{id, en, ru, sentence}, ...]
let vcData        = null;  // persisted: { practiced: {id: dateStr}, browse: {id: 'known'|'review'} }

// Session
let sessionWords  = [];    // subset of allCards for this session
let sessionIdx    = 0;     // current word index
let currentStage  = 1;     // 1–4
let retryCount    = 0;
let stage3Prompt  = '';    // English prompt sentence generated by API

// Browse
let browseIdx     = 0;
let browseFlipped = false;

// Voice
let ruVoice       = null;
let hasVoice      = false;
let recognition   = null;
let isRecording   = false;
let currentSpeakText = '';

// Current mode ('session' | 'browse')
let currentMode   = 'session';

// ── Persistence ────────────────────────────────────────────────
function loadData() {
  try {
    const raw = localStorage.getItem(VC_KEY);
    return raw ? JSON.parse(raw) : { practiced: {}, browse: {} };
  } catch { return { practiced: {}, browse: {} }; }
}

function saveData() {
  localStorage.setItem(VC_KEY, JSON.stringify(vcData));
}

function today() {
  return new Date().toISOString().split('T')[0];
}

// ── CSV parser (copied from flashcards.js) ─────────────────────
function splitCSVRow(line) {
  const result = [];
  let cell = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      if (inQuotes && line[i + 1] === '"') { cell += '"'; i++; }
      else inQuotes = !inQuotes;
    } else if (ch === ',' && !inQuotes) {
      result.push(cell);
      cell = '';
    } else {
      cell += ch;
    }
  }
  result.push(cell);
  return result;
}

function parseCSV(text) {
  const lines = text.trim().split(/\r?\n/);
  if (lines.length < 2) return [];

  const headers = splitCSVRow(lines[0]).map(h => h.toLowerCase().trim());
  const find = (candidates) =>
    candidates.map(k => headers.indexOf(k)).find(i => i >= 0) ?? -1;

  const enCol  = find(['en', 'english', 'translation', 'meaning', 'definition']);
  const ruCol  = find(['ru', 'russian', 'word', 'term', 'russian_word']);
  const senCol = find(['sentence', 'example', 'context', 'phrase', 'example_sentence']);

  const col0 = enCol >= 0 ? enCol : 0;
  const col1 = ruCol >= 0 ? ruCol : 1;

  const cards = [];
  for (let i = 1; i < lines.length; i++) {
    const cols = splitCSVRow(lines[i]);
    const en = (cols[col0] || '').trim();
    const ru = (cols[col1] || '').trim();
    if (!en && !ru) continue;
    cards.push({
      id:       i - 1,
      en,
      ru,
      sentence: senCol >= 0 ? (cols[senCol] || '').trim() : ''
    });
  }
  return cards;
}

// ── Voice init ─────────────────────────────────────────────────
function initVoice() {
  if (!('speechSynthesis' in window)) return;

  function findRuVoice() {
    const voices = speechSynthesis.getVoices();
    ruVoice = voices.find(v => v.lang.startsWith('ru')) || null;
    hasVoice = !!ruVoice;
  }

  findRuVoice();
  speechSynthesis.addEventListener('voiceschanged', findRuVoice);
}

function speak(text, onEnd) {
  if (!hasVoice || !text) { if (onEnd) onEnd(); return; }
  speechSynthesis.cancel();
  const utt = new SpeechSynthesisUtterance(text);
  utt.voice = ruVoice;
  utt.lang  = 'ru-RU';
  utt.rate  = 0.9;
  if (onEnd) utt.onend = onEnd;
  speechSynthesis.speak(utt);
}

function speakEN(text, onEnd) {
  speechSynthesis.cancel();
  const utt = new SpeechSynthesisUtterance(text);
  utt.lang = 'en-US';
  if (onEnd) utt.onend = onEnd;
  speechSynthesis.speak(utt);
}

// ── STT init ───────────────────────────────────────────────────
function initRecognition(lang) {
  const SR = window.SpeechRecognition || window.webkitSpeechRecognition;
  if (!SR) return null;
  const r = new SR();
  r.lang = lang;
  r.interimResults = false;
  r.maxAlternatives = 1;
  return r;
}

function startRecording(lang) {
  if (isRecording) { stopRecording(); return; }
  recognition = initRecognition(lang);
  if (!recognition) return;

  $('vcMicBtn').classList.add('vc-icon-btn--active');
  isRecording = true;

  recognition.onresult = (e) => {
    const transcript = e.results[0][0].transcript.trim();
    if (transcript.toLowerCase() === 'stop') {
      stopRecording();
      return;
    }
    $('vcInput').value = transcript;
    stopRecording();
  };

  recognition.onerror = () => stopRecording();
  recognition.onend   = () => { isRecording = false; $('vcMicBtn').classList.remove('vc-icon-btn--active'); };
  recognition.start();
}

function stopRecording() {
  if (recognition) try { recognition.stop(); } catch {}
  isRecording = false;
  $('vcMicBtn').classList.remove('vc-icon-btn--active');
}

// ── Word selection ─────────────────────────────────────────────
function shuffle(arr) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

function selectSessionWords() {
  const t = today();
  const unpracticed = allCards.filter(c => !vcData.practiced[c.id]);
  const dueReview   = allCards.filter(c => {
    const d = vcData.practiced[c.id];
    return d && d !== t;
  });

  shuffle(unpracticed);
  shuffle(dueReview);

  const pool = [...unpracticed, ...dueReview];
  return pool.slice(0, SESSION_SIZE);
}

// ── Stats ──────────────────────────────────────────────────────
function renderStats() {
  const total      = allCards.length;
  const practiced  = Object.keys(vcData.practiced).length;
  const t          = today();
  const doneToday  = Object.values(vcData.practiced).filter(d => d === t).length;

  $('vcStats').innerHTML = `
    <div class="vc-stat"><span class="vc-stat-num">${practiced}</span><span class="vc-stat-lbl">practiced</span></div>
    <div class="vc-stat"><span class="vc-stat-num">${total - practiced}</span><span class="vc-stat-lbl">remaining</span></div>
    <div class="vc-stat"><span class="vc-stat-num">${doneToday}</span><span class="vc-stat-lbl">today</span></div>
  `;
}

// ── Screen helpers ─────────────────────────────────────────────
function showScreen(id) {
  ['vcWelcome', 'vcLoading', 'vcSession', 'vcComplete', 'vcBrowse'].forEach(s => {
    $(s).hidden = s !== id;
  });
}

// ── Session flow ───────────────────────────────────────────────
function startSession() {
  sessionWords = selectSessionWords();
  if (sessionWords.length === 0) {
    $('vcCompleteMsg').textContent = 'No words available. Add more flashcards or come back tomorrow.';
    showScreen('vcComplete');
    return;
  }
  sessionIdx = 0;
  loadWord(sessionIdx);
  showScreen('vcSession');
  $('vcHeaderActions').hidden = false;
  $('vcModeToggleBtn').textContent = 'Browse mode';
}

function loadWord(idx) {
  currentStage = 1;
  retryCount   = 0;
  stage3Prompt = '';
  updateProgress(idx);
  renderStage1(sessionWords[idx]);
}

function updateProgress(idx) {
  const total = sessionWords.length;
  $('vcProgressFill').style.width = `${(idx / total) * 100}%`;
  $('vcProgressText').textContent = `Word ${idx + 1} / ${total}`;
}

function advanceWord() {
  sessionIdx++;
  if (sessionIdx >= sessionWords.length) {
    finishSession();
  } else {
    loadWord(sessionIdx);
  }
}

function advanceStage() {
  currentStage++;
  retryCount = 0;
  const card = sessionWords[sessionIdx];
  if (currentStage === 2) renderStage2(card);
  else if (currentStage === 3) renderStage3(card);
  else if (currentStage === 4) renderStage4(card);
  else {
    markPracticed(card);
    advanceWord();
  }
}

function markPracticed(card) {
  vcData.practiced[card.id] = today();
  saveData();
}

function finishSession() {
  const count = sessionWords.length;
  sessionWords.forEach(c => markPracticed(c));
  $('vcCompleteMsg').textContent = `You trained ${count} word${count !== 1 ? 's' : ''}. Keep it up!`;
  renderStats();
  showScreen('vcComplete');
  $('vcHeaderActions').hidden = true;
}

// ── Stage renderers ────────────────────────────────────────────
const STAGE_NAMES = ['Contextual Exposure', 'Controlled Recognition', 'Prompted Production', 'Free Production'];

function setStageHeader(stage) {
  $('vcStageBadge').textContent = `Stage ${stage}`;
  $('vcStageTitle').textContent = STAGE_NAMES[stage - 1];
}

function clearSession() {
  $('vcContent').innerHTML  = '';
  $('vcFeedback').hidden    = true;
  $('vcFeedback').innerHTML = '';
  $('vcInputRow').hidden    = true;
  $('vcActions').hidden     = true;
  $('vcSpeakerRow').hidden  = true;
  $('vcInput').value        = '';
}

// ── Stage 1: Contextual Exposure ───────────────────────────────
function renderStage1(card) {
  setStageHeader(1);
  clearSession();

  const hasSentence = !!card.sentence;
  const question    = hasSentence
    ? 'What is the overall meaning of this sentence?'
    : `What does "${card.en}" mean in Russian?`;

  let html = '';
  if (hasSentence) {
    html += `<p class="vc-sentence-ru">${escHtml(card.sentence)}</p>`;
    html += `<p class="vc-label">Translation hint: <span class="vc-word-en">${escHtml(card.en)}</span> = <span class="vc-word-ru">${escHtml(card.ru)}</span></p>`;
  } else {
    html += `<p class="vc-word-pair"><span class="vc-word-en">${escHtml(card.en)}</span> <span class="vc-sep">→</span> <span class="vc-word-ru">${escHtml(card.ru)}</span></p>`;
  }
  html += `<p class="vc-question">${escHtml(question)}</p>`;
  $('vcContent').innerHTML = html;

  // Speaker: speak sentence or Russian word
  const speakText = hasSentence ? card.sentence : card.ru;
  currentSpeakText = speakText;
  $('vcSpeakLabel').textContent = hasSentence ? 'Play sentence' : 'Play word';
  $('vcSpeakerRow').hidden = !hasVoice;

  // Auto-play
  if (hasVoice) speak(speakText);

  // Show input
  $('vcInputRow').hidden = false;
  $('vcInput').placeholder = 'Type your understanding…';

  // Mic: English (answering comprehension in English)
  $('vcMicBtn').onclick = () => startRecording('en-US');
  $('vcSubmitBtn').onclick = () => submitStage1(card, question);
  $('vcInput').onkeydown = (e) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); submitStage1(card, question); } };
}

async function submitStage1(card, question) {
  const answer = $('vcInput').value.trim();
  if (!answer) return;

  setLoading(true);
  const sentence = card.sentence || `${card.en} means ${card.ru}`;
  const res = await callAPI('stage1-check', { sentence, question, answer });
  setLoading(false);

  if (!res) return;
  const passed = res.includes('[PASS]');
  showFeedback(res.replace(/\[(PASS|RETRY)\]/g, '').trim(), passed);

  if (passed) {
    showNext(() => advanceStage());
  } else {
    retryCount++;
    if (retryCount >= MAX_RETRIES) {
      showNext(() => advanceStage());
    } else {
      showRetryInput();
    }
  }
}

// ── Stage 2: Controlled Recognition ───────────────────────────
function createGappedSentence(card) {
  if (!card.sentence) return null;
  const ru = card.ru.trim();

  // Try exact match (case-insensitive)
  const idx = card.sentence.toLowerCase().indexOf(ru.toLowerCase());
  if (idx >= 0) {
    return {
      gapped: card.sentence.slice(0, idx) + '___' + card.sentence.slice(idx + ru.length),
      target: ru
    };
  }

  // Try matching first token of ru
  const firstToken = ru.split(/\s+/)[0];
  const idx2 = card.sentence.toLowerCase().indexOf(firstToken.toLowerCase());
  if (idx2 >= 0) {
    return {
      gapped: card.sentence.slice(0, idx2) + '___' + card.sentence.slice(idx2 + firstToken.length),
      target: firstToken
    };
  }

  return null;
}

function renderStage2(card) {
  setStageHeader(2);
  clearSession();

  const gap = createGappedSentence(card);
  let html = '';
  let question, speakText;

  if (gap) {
    html += `<p class="vc-sentence-ru">${escHtml(gap.gapped)}</p>`;
    html += `<p class="vc-label">Fill in the gap with the Russian word for: <span class="vc-word-en">${escHtml(card.en)}</span></p>`;
    question   = gap.gapped;
    speakText  = card.ru;
  } else {
    html += `<p class="vc-word-pair"><span class="vc-word-en">${escHtml(card.en)}</span></p>`;
    html += `<p class="vc-label">Type the Russian word or phrase:</p>`;
    question  = `Type the Russian for: ${card.en}`;
    speakText = card.ru;
  }
  $('vcContent').innerHTML = html;

  currentSpeakText = speakText;
  $('vcSpeakLabel').textContent = 'Hear the word';
  $('vcSpeakerRow').hidden = !hasVoice;

  $('vcInputRow').hidden = false;
  $('vcInput').placeholder = 'Type in Russian…';

  $('vcMicBtn').onclick = () => startRecording('ru-RU');
  $('vcSubmitBtn').onclick = () => submitStage2(card, gap, question);
  $('vcInput').onkeydown = (e) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); submitStage2(card, gap, question); } };
}

async function submitStage2(card, gap, gappedSentence) {
  const answer = $('vcInput').value.trim();
  if (!answer) return;

  setLoading(true);
  const target = gap ? gap.target : card.ru;
  const res = await callAPI('stage2-check', { gappedSentence: gappedSentence || card.en, target, answer });
  setLoading(false);

  if (!res) return;
  const passed = res.includes('[PASS]');
  showFeedback(res.replace(/\[(PASS|RETRY)\]/g, '').trim(), passed);

  if (passed) {
    showNext(() => advanceStage());
  } else {
    retryCount++;
    if (retryCount >= MAX_RETRIES) {
      showFeedback(`The answer is: ${escHtml(card.ru)}`, false);
      showNext(() => advanceStage());
    } else {
      showRetryInput();
    }
  }
}

// ── Stage 3: Prompted Production ──────────────────────────────
function renderStage3(card) {
  setStageHeader(3);
  clearSession();

  $('vcContent').innerHTML = `<p class="vc-label">Generating a sentence prompt…</p><div class="vc-spinner vc-spinner--sm"></div>`;

  generateStage3Prompt(card);
}

async function generateStage3Prompt(card) {
  const res = await callAPI('stage3-generate', { en: card.en, ru: card.ru });

  if (!res) {
    // Fallback: use a canned prompt
    stage3Prompt = `Translate: "${card.en}"`;
  } else {
    stage3Prompt = res.trim();
  }

  let html = `<p class="vc-sentence-en">${escHtml(stage3Prompt)}</p>`;
  html += `<p class="vc-label">Translate this sentence into Russian (using <span class="vc-word-ru">${escHtml(card.ru)}</span>):</p>`;
  $('vcContent').innerHTML = html;

  currentSpeakText = card.ru;
  $('vcSpeakLabel').textContent = 'Hear the word';
  $('vcSpeakerRow').hidden = !hasVoice;

  $('vcInputRow').hidden = false;
  $('vcInput').placeholder = 'Type your Russian translation…';

  $('vcMicBtn').onclick = () => startRecording('ru-RU');
  $('vcSubmitBtn').onclick = () => submitStage3(card);
  $('vcInput').onkeydown = (e) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); submitStage3(card); } };
}

async function submitStage3(card) {
  const answer = $('vcInput').value.trim();
  if (!answer) return;

  setLoading(true);
  const res = await callAPI('stage3-check', { promptSentence: stage3Prompt, target: card.ru, answer });
  setLoading(false);

  if (!res) return;
  const passed = res.includes('[PASS]');
  showFeedback(res.replace(/\[(PASS|RETRY)\]/g, '').trim(), passed);

  if (passed) {
    showNext(() => advanceStage());
  } else {
    retryCount++;
    if (retryCount >= MAX_RETRIES) {
      showNext(() => advanceStage());
    } else {
      showRetryInput();
    }
  }
}

// ── Stage 4: Free Production ───────────────────────────────────
function renderStage4(card) {
  setStageHeader(4);
  clearSession();

  let html = `<p class="vc-word-pair"><span class="vc-word-en">${escHtml(card.en)}</span> <span class="vc-sep">→</span> <span class="vc-word-ru">${escHtml(card.ru)}</span></p>`;
  html += `<p class="vc-label">Write an original Russian sentence using this word:</p>`;
  $('vcContent').innerHTML = html;

  currentSpeakText = card.ru;
  $('vcSpeakLabel').textContent = 'Hear the word';
  $('vcSpeakerRow').hidden = !hasVoice;

  $('vcInputRow').hidden = false;
  $('vcInput').placeholder = 'Write your own Russian sentence…';

  $('vcMicBtn').onclick = () => startRecording('ru-RU');
  $('vcSubmitBtn').onclick = () => submitStage4(card);
  $('vcInput').onkeydown = (e) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); submitStage4(card); } };
}

async function submitStage4(card) {
  const answer = $('vcInput').value.trim();
  if (!answer) return;

  setLoading(true);
  const res = await callAPI('stage4-check', { en: card.en, ru: card.ru, answer });
  setLoading(false);

  if (!res) return;
  const passed = res.includes('[PASS]');
  showFeedback(res.replace(/\[(PASS|RETRY)\]/g, '').trim(), passed);

  if (passed) {
    showNext(() => advanceStage());
  } else {
    retryCount++;
    if (retryCount >= MAX_RETRIES) {
      showNext(() => advanceStage());
    } else {
      showRetryInput();
    }
  }
}

// ── UI helpers ─────────────────────────────────────────────────
function showFeedback(text, passed) {
  $('vcFeedback').innerHTML  = escHtml(text);
  $('vcFeedback').className  = `vc-feedback ${passed ? 'vc-feedback--pass' : 'vc-feedback--retry'}`;
  $('vcFeedback').hidden     = false;
  $('vcInputRow').hidden     = true;
}

function showRetryInput() {
  $('vcInput').value       = '';
  $('vcInputRow').hidden   = false;
  $('vcActions').hidden    = true;
}

function showNext(fn) {
  $('vcActions').hidden  = false;
  $('vcNextBtn').onclick = fn;
  $('vcInputRow').hidden = true;
}

function setLoading(on) {
  $('vcSubmitBtn').disabled = on;
  $('vcSubmitBtn').textContent = on ? 'Checking…' : 'Submit →';
}

function escHtml(s) {
  return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

// ── API call ───────────────────────────────────────────────────
async function callAPI(mode, payload) {
  try {
    const res = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ mode, ...payload })
    });
    const data = await res.json();
    if (!res.ok) { console.error(data.error); return null; }
    return data.content;
  } catch (err) {
    console.error(err);
    return null;
  }
}

// ── Browse mode ────────────────────────────────────────────────
function startBrowse() {
  browseIdx     = 0;
  browseFlipped = false;
  renderBrowseCard();
  showScreen('vcBrowse');
  $('vcHeaderActions').hidden = false;
  $('vcModeToggleBtn').textContent = 'Session mode';
}

function renderBrowseCard() {
  const card = allCards[browseIdx];
  $('vcBrowseCounter').textContent = `${browseIdx + 1} / ${allCards.length}`;
  $('vcCardEn').textContent        = card.en;
  $('vcCardRu').textContent        = card.ru;
  $('vcCardSentence').textContent  = card.sentence || '';
  $('vcCardSentence').hidden       = !card.sentence;

  // Reset flip
  browseFlipped = false;
  $('vcCard').classList.remove('vc-card--flipped');

  // Known/review state
  const mark = vcData.browse[card.id];
  $('vcMarkKnown').classList.toggle('vc-mark-btn--known-active',   mark === 'known');
  $('vcMarkReview').classList.toggle('vc-mark-btn--review-active', mark === 'review');
}

// ── Welcome mode toggle ────────────────────────────────────────
function setupModeButtons() {
  document.querySelectorAll('.vc-mode-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      document.querySelectorAll('.vc-mode-btn').forEach(b => b.classList.remove('vc-mode-btn--active'));
      btn.classList.add('vc-mode-btn--active');
      currentMode = btn.dataset.mode;
      $('vcStartBtn').textContent = currentMode === 'browse' ? 'Browse cards →' : 'Start session →';
    });
  });
}

// ── Initialise ─────────────────────────────────────────────────
async function init() {
  showScreen('vcLoading');
  $('vcHeaderActions').hidden = true;

  try {
    const res  = await fetch(DATA_URL);
    const text = await res.text();
    allCards   = parseCSV(text);
  } catch {
    allCards = [];
  }

  vcData = loadData();
  initVoice();

  renderStats();
  setupModeButtons();
  showScreen('vcWelcome');

  // Welcome actions
  $('vcStartBtn').addEventListener('click', () => {
    if (currentMode === 'browse') startBrowse();
    else startSession();
  });

  // Header mode toggle
  $('vcModeToggleBtn').addEventListener('click', () => {
    if (currentMode === 'browse' || $('vcBrowse').hidden === false) {
      // Switch to session
      currentMode = 'session';
      startSession();
    } else {
      // Switch to browse
      currentMode = 'browse';
      startBrowse();
    }
  });

  // Session: speak button
  $('vcSpeakBtn').addEventListener('click', () => speak(currentSpeakText));

  // Session: new session button
  $('vcNewSessionBtn').addEventListener('click', () => {
    renderStats();
    showScreen('vcWelcome');
    $('vcHeaderActions').hidden = true;
  });

  // Browse: navigation
  $('vcBrowsePrev').addEventListener('click', () => {
    if (browseIdx > 0) { browseIdx--; renderBrowseCard(); }
  });
  $('vcBrowseNext').addEventListener('click', () => {
    if (browseIdx < allCards.length - 1) { browseIdx++; renderBrowseCard(); }
  });

  // Browse: flip
  $('vcCard').addEventListener('click', () => {
    browseFlipped = !browseFlipped;
    $('vcCard').classList.toggle('vc-card--flipped', browseFlipped);
  });

  // Browse: speak on back
  $('vcBrowseSpeakBtn').addEventListener('click', (e) => {
    e.stopPropagation();
    const card = allCards[browseIdx];
    speak(card.ru);
  });

  // Browse: mark buttons
  $('vcMarkKnown').addEventListener('click', () => {
    const id = allCards[browseIdx].id;
    vcData.browse[id] = 'known';
    saveData();
    $('vcMarkKnown').classList.add('vc-mark-btn--known-active');
    $('vcMarkReview').classList.remove('vc-mark-btn--review-active');
    if (browseIdx < allCards.length - 1) { browseIdx++; renderBrowseCard(); }
  });
  $('vcMarkReview').addEventListener('click', () => {
    const id = allCards[browseIdx].id;
    vcData.browse[id] = 'review';
    saveData();
    $('vcMarkReview').classList.add('vc-mark-btn--review-active');
    $('vcMarkKnown').classList.remove('vc-mark-btn--known-active');
    if (browseIdx < allCards.length - 1) { browseIdx++; renderBrowseCard(); }
  });

  // Browse: back button
  $('vcBrowseEndBtn').addEventListener('click', () => {
    renderStats();
    showScreen('vcWelcome');
    $('vcHeaderActions').hidden = true;
    currentMode = 'session';
    document.querySelectorAll('.vc-mode-btn').forEach(b => {
      b.classList.toggle('vc-mode-btn--active', b.dataset.mode === 'session');
    });
    $('vcStartBtn').textContent = 'Start session →';
  });

  // Keyboard shortcut: left/right arrows in browse
  document.addEventListener('keydown', (e) => {
    if ($('vcBrowse').hidden) return;
    if (e.key === 'ArrowLeft'  && browseIdx > 0)                      { browseIdx--; renderBrowseCard(); }
    if (e.key === 'ArrowRight' && browseIdx < allCards.length - 1)    { browseIdx++; renderBrowseCard(); }
    if (e.key === ' ')                                                  { e.preventDefault(); $('vcCard').click(); }
  });
}

document.addEventListener('DOMContentLoaded', init);
